name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VSCODE_MARKETPLACE_PAT }}
          args: "publish -p $VSCE_TOKEN"
